[package]
name = "kiosk-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
dirs = "6"
serde.workspace = true
toml = "0.8"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
