version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      rust-patches:
        patterns: ["*"]
        update-types: ["patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["dependencies"]
    groups:
      gha-patches:
        patterns: ["*"]
        update-types: ["patch"]
