[package]
name = "kiosk"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
kiosk-core = { path = "../kiosk-core" }
kiosk-tui = { path = "../kiosk-tui" }
ratatui = "0.29"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
